# Generated by Django 4.2.4 on 2023-08-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Имя автора")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Краткая биография"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="authors/default.jpg",
                        upload_to="authors/photos",
                        verbose_name="Фото автора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название категории"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название книги"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        default="books/default.jpg",
                        upload_to="books/covers",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="book_author",
                        to="books.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="book_category",
                        to="books.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
